# Generated by Django 3.2 on 2021-04-25 16:33

from django.db import migrations
from django.utils import timezone


def add_data(apps, schema_editor):
    Student = apps.get_model("homework_model", "Student")
    student = Student(first_name="Lev", last_name="Sokolov")
    student.save()

    Teacher = apps.get_model("homework_model", "Teacher")
    teacher = Teacher(first_name="Daniil", last_name="Shadrin")
    teacher.save()

    Homework = apps.get_model("homework_model", "Homework")
    homework_task = Homework(
        text="Learn Django",
        deadline=timezone.now(),
        created=timezone.now(),
        teacher=teacher,
    )
    homework_task.save()

    HomeworkResult = apps.get_model("homework_model", "HomeworkResult")
    homework_result = HomeworkResult(
        homework=homework_task,
        solution="I have done this hw",
        author=student,
        created=timezone.now(),
    )
    homework_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ("homework_model", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
